### ISSUE TITLE
Persons & Organizations tables are empty on load

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/People#12]
Steps to reproduce:

1. Run People app inside Launcher app.
2. Open page http://localhost:8080/people/organizations or http://localhost:8080/people/persons by inputting url, not by clicking the left menu.

The page is empty. Something is not loading here.
I tried to debug and see what is happening and ended up with this issue:
https://github.com/Starcounter/Starcounter/issues/2626

This did not happen before Alexey's changes:
http://starcounter.io/nightly-changes/changes-regarding-polyjuice-applications-starting-after-build-2-0-3099/

**Comment by alemoi** [comment]
Thanks for reporting! I will check this one right away.

**Comment by alemoi** [comment]
And I assume you have installed the latest version: 2.0.3100.3

**Comment by miyconst** [comment]
@alemoi, yes, it is the latest version of SC.

**Comment by alemoi** [comment]
Unfortunately can't reproduce in my environment, works fine for me. I will ask @warpech if he has the problem.

**Comment by miyconst** [comment]
@alemoi, okay, I will reboot pc, reinstall SC, check if it still there.

**Comment by warpech** [comment]
Works OK for me. My setup:
- Starcounter 2.0.3100.3
- Launcher built from current develop branch (https://github.com/Polyjuice/Launcher/commit/4c57eaa07bce3d922dac88d3cc6b2beb422a56f2)
- People build from current develop branch (https://github.com/Polyjuice/People/commit/f82cfa1e73c6239b6fa59017e71dd03e69d874ed)

@miyconst If it still doesn't work for you, let's connect on Hangout.

**Comment by miyconst** [comment]
The issue is gone after updating Launcher.
