### ISSUE TITLE
People app resets h1, h2, .... globally

### ISSUE THREAD

**Issue by warpech** [Polyjuice/People#16]
In CSS file https://github.com/Polyjuice/People/blob/master/src/People/wwwroot/People/css/people.css there is a global reset of styles for h1, h2, h3, ...

It should only change styles for People app templates

**Comment by warpech** [comment]
@miyconst can you fix that?

**Comment by miyconst** [comment]
The `people.css` file is no longer required, removed it.
Also removed `people-old.css` and `animation.css`.
