### ISSUE TITLE
Appear in other appps as a small form

### ISSUE THREAD

**Issue by warpech** [Polyjuice/People#4]
People partial should appear in other apps (such as Skyper) as a small icon. Putting the mouse cursor over that icon should show small bubble with person's business card. The business card should include a link to People workspace.

Later I will add a UI wireframe to this task.

**Comment by miyconst** [comment]
The application looks bad and not user friendly.
Maybe it is better to rework the app before build it in another app?

**Comment by warpech** [comment]
Yes, of course, this issue was just created to show the direction to go. Do you need some guidance or have already some ideas what to do?

**Comment by miyconst** [comment]
@warpech, I have made some GUI changes.
It would be nice to get some feedback before I go further.

**Comment by miyconst** [comment]
@warpech is the issue still relevant?

**Comment by warpech** [comment]
Yes, but let's continue when Starcounter adds a way to know the nesting level of a partial inside of a X.GET handler (I will bump this issue once that's done)

**Comment by alemoi** [comment]
https://github.com/Polyjuice/Polyjuice/issues/22

**Comment by alemoi** [comment]
Here is the related issue: https://github.com/Polyjuice/Polyjuice/issues/22

**Comment by warpech** [comment]
This was partially done by using `CallLevel` in combination with https://github.com/Polyjuice/People/blob/master/src/People/wwwroot/People/viewmodels/OrganizationSmallPage.html to show small info about Organisation in Products app.

Just before a demo on Apr 22 we decided to replace that with `OrganizationEmptyPage.html`, because it was not possible to relayout.

@miyconst could you revert `OrganizationEmptyPage.html` so we can test `CallLevel` again?

**Comment by miyconst** [comment]
@warpech we still can't edit layout of OrganizationPage inside Products app, should I remove it anyway?

**Comment by warpech** [comment]
No, we need to get layout editing possible there first. Why doesn't it work? Could you make an issue about that?

**Comment by miyconst** [comment]
It does not work because it is a table, not set of divs.

**Comment by miyconst** [comment]
I am not sure that we actually need it in there. It is just a list of suppliers on the product details page. We should not be able to edit a supplier from that page, I guess.

**Comment by warpech** [comment]
Even if we not need this small edit form in the Products app, it does not mean that the "Organization" page should always be empty if accessed at CallLevel > 1 as it is now.

So my proposal is to:

1. Restore `OrganizationSmallPage` the Organization page is requested at CallLevel > 1
2. Change the Products page to use laid-out `<div>`s instead of `<table>`. Can you create an issue for that?
3. Someone who does not want organization form in Products page will hide it using the layout editor.

**Comment by miyconst** [comment]
Okay.

Here is the issue: https://github.com/Polyjuice/Products/issues/3.
Should I take this and that one?

**Comment by warpech** [comment]
Yes. 

To remind, this ticket is about both displaying both Organization and Person page as a small form at CallLevel > 1.

**Comment by miyconst** [comment]
Done.

Now a small and nice Organization page with first address, email address, phone number appears in Products app in Suppliers section.

After applying some styles the page looks like this:
![product-page](https://cloud.githubusercontent.com/assets/6435556/7586565/d24db580-f8b6-11e4-9123-070a3132ccf3.png)

**Comment by miyconst** [comment]
A problem with `Handle.CallLevel` discovered.

The Product's page have the following structure:

1. Product page - level 1.
2. Supplier page - level 2.
3. Organization page - level 3.

In people Application I check `Handle.CallLevel` and depending on that return full or small organization page. Everything works fine on page load, but when user clicks "Add supplier" button and a `Self.GET` request send for the new supplier, then People app receives a request with `Handle.CallLevel` equals to `1`.

I have talked to @alemoi about this, but we didn't come up with a good solution.

Right now the only one solution, is to separate OrganizationPage and OrganizationSmallPage into two different handlers.

**Comment by warpech** [comment]
@alemoi unless you have a cleaner solution, would it be possible to force `CallLevel` on when making a `Self.GET` request? 

Supplier page (level 2) could rememer its `CallLevel` in a variable and then request the Organization page at that level + 1.

**Comment by miyconst** [comment]
+1, I suggested the same solution.

**Comment by alemoi** [comment]
After a discussion we came to conclusion to expose `Handle.CallLevel` for modification. The following unit example speaks for itself:
```c#
            Handle.GET("/level8", (Request req) => {

                Assert.IsTrue(Handle.CallLevel == 8);

                return 200;
            });

            Handle.GET("/level3", (Request req) => {

                Assert.IsTrue(Handle.CallLevel == 3);

                Handle.CallLevel = Handle.CallLevel + 4;
                Assert.IsTrue(Handle.CallLevel == 7);

                Response resp = Self.GET("/level8");
                Assert.AreEqual(resp.IsSuccessStatusCode, true);

                Assert.IsTrue(Handle.CallLevel == 7);

                return 200;
            });
```

**Comment by miyconst** [comment]
Tested, works good so far.

**Comment by alemoi** [comment]
:+1:
