### ISSUE TITLE
System.IO.IOException exception when trying to access Db.SQL from Json model class

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/People#7]
I have changed this code:

```csharp
Handle.GET("/people/partials/companies", () => {
	CompaniesPage c = new CompaniesPage() {
		Html = "/companies.html"
	};
	var companies = SQL<Company>("SELECT c FROM People.Company c");
	c.Companies.Data = companies;

	return c;
});
```

to:

```csharp
Handle.GET("/people/partials/companies", () => {
	CompaniesPage c = new CompaniesPage() {
		Html = "/companies.html"
	};

	c.RefreshCompanies();

	return c;
});
```

and here is the RefreshCompanies method:

```csharp
public void RefreshCompanies() {
	this.Data = Db.SQL<Company>("SELECT c FROM People.Company c");
}
```

It rises exception on query execution:

An exception of type 'System.IO.IOException' occurred in Starcounter.dll but was not handled in user code.

Detailed message: {"no connection to Prolog Server"}

What this exception means?

**Comment by k-rus** [comment]
Thank you for submitting the issue.
Current legacy SQL processor uses Prolog to parse and type check queries. The prolog program is run in a separate process. The error indicates that there is a problem on the way to communicate with the prolog process. It is difficult to say what is the reason for the error.

**Comment by k-rus** [comment]
How can we reproduce the issue?

**Comment by k-rus** [comment]
May be @chrhol can look at it at first place, since the error is sensitive to auto-binding.

**Comment by miyconst** [comment]
Unfortunately, but I can't reproduce the error.

I reproduced it many times. It was working inside Handle.GET method and rising the exception inside CompaniesPage class.

After pc reboot all of the combinations work and I could not find a way to rise the exception again. 
The source code is updated, so you may have a look.

**Comment by miyconst** [comment]
What is the difference between 
```csharp
SQL<Company>("SELECT c FROM People.Company c");
```
and
```csharp
Db.SQL<Company>("SELECT c FROM People.Company c");
```

Two methods are defined in different classes and return different result:
```csharp
namespace Starcounter.Advanced {
    public class StarcounterBase : Handle {
		...
        public static Rows<dynamic> SQL(string query, params object[] args);
        public static Rows<T> SQL<T>(string query, params object[] args);
    }
}

namespace Starcounter {
    public static class Db {
        public static QueryResultRows<object> SQL(string query, params object[] values);
        public static QueryResultRows<T> SQL<T>(string query, params object[] values);
    }
}
```

In the application Db.SQL and SQL both work the same.

**Comment by chrhol** [comment]
The only difference between the two are the type returned. Both will return instances of `QueryResultRows<T>` and actually the methods in `StarcounterBase` will call the corresponding method in class `Db` but through an interface to allow dependency-injection for some functionality that is needed where a dependency to the Starcounter project cannot be added, like in Starcounter.XSON.

Then again, I don't really know the thought behind the class `StarcounterBase`, and it should probably be revisited and cleaned up. The methods in your question just feels like it adds confusion instead of helping.

**Comment by miyconst** [comment]
@chrhol, which one is preferable and which one I should use?

**Comment by chrhol** [comment]
> @chrhol, which one is preferable and which one I should use?

Personally, I would use `Db.SQL` and `Db.SQL<T>`. I see no real reason to have an other set of these functions.

**Comment by miyconst** [comment]
@chrhol, I will do the same, thank you.

**Comment by miyconst** [comment]
I close the issue, because I could not reproduce the exception any more.

**Comment by dan31** [comment]
@chrhol, can you add a separate issue on revising  Starcounter.Advanced?
