### ISSUE TITLE
Add contact information

### ISSUE THREAD

**Issue by warpech** [Polyjuice/People#8]
There should be contact information management in People app. A person/company can have one or more of the following:
- phone number with a role (work, home, mobile, etc) and dial code
- email with a role (work, home, mobile, etc)
- address with a role

See the UI patterns in Gmail "Contacts" feature.

[Pmail](https://github.com/warpech/pmail) app has such contact editing features, though it was not updated in a year.

**Comment by miyconst** [comment]
- [x] Added new classes: ContactInfo, ContactInfoType (email, phone, address), ContactInfoRole (personal, home, work).
- [x] Removed email from Contact class.
- [x] Added contact infos to Contact's page.
- [ ] Company contact infos left.

**Comment by miyconst** [comment]
Is this issue still actual?
